/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu Aug 01 13:28:54 2019. */

#include "message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t leuville_Uplink_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, leuville_Uplink, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, leuville_Uplink, battery, type, 0),
    PB_LAST_FIELD
};

const pb_field_t leuville_Downlink_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, leuville_Downlink, pingDelay, pingDelay, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
